@WorkshopAPI_HostAddress = http://localhost:5230
@date = 2030-01-01T09:00:00Z

### GET all workshops (supports ?search=)
GET {{WorkshopAPI_HostAddress}}/api/workshops?search=
Accept: application/json

### GET workshop by id
@workshopId = 00000000-0000-0000-0000-000000000000
GET {{WorkshopAPI_HostAddress}}/api/workshops/{{workshopId}}
Accept: application/json

### POST create workshop
POST {{WorkshopAPI_HostAddress}}/api/workshops
Content-Type: application/json

{
  "title": "Intro to ASP.NET Core",
  "description": "Hands-on CRUD API workshop.",
  "date": "{{date}}",
  "maxParticipants": 25
}

### PUT update workshop
PUT {{WorkshopAPI_HostAddress}}/api/workshops/{{workshopId}}
Content-Type: application/json

{
  "title": "Updated workshop title",
  "description": "Updated description",
  "date": "{{date}}",
  "maxParticipants": 40
}

### DELETE workshop
DELETE {{WorkshopAPI_HostAddress}}/api/workshops/{{workshopId}}
Accept: application/json

